AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  rosetta

  Sample SAM Template for rosetta

Globals:
  Function:
    Runtime: python3.8
    Timeout: 10
    Handler: app.lambda_handler
    MemorySize: 128
    # TODO: revisit and internal VPC configuration
    # VpcConfig: XYZ

Resources:
  # TODO Add a well defined statemachine here - refer to the file ./statemachine/statemachine-description.txt


  FileValidator:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/file_validator/
#      Handler: app.lambda_handler
#      Runtime: python3.8
#      Timeout: 10

# template refernce:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-template-anatomy.html