AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  rosetta

  Sample SAM Template for rosetta

Resources:
  StockTradingStateMachine:
    Type: AWS::Serverless::StateMachine # More info about State Machine Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html
    Properties:
      DefinitionUri: statemachine/rosetta_asl.json
      DefinitionSubstitutions:
        FileValidatorFunctionArn: !GetAtt FileValidatorFunction.Arn
      Policies: # Find out more about SAM policy templates: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
        - LambdaInvokePolicy:
            FunctionName: !Ref FileValidator
  FileValidator:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/file_validator/
      Handler: app.lambda_handler
      Runtime: python3.8
      Timeout: 10


